### ISSUE TITLE
CSS problem on "Your Projects" page

### ISSUE THREAD

**Issue by jurgenhaas** [unicorn-fail/dreditor#242]
On https://www.drupal.org/project/user there is the following problem that a Dreditor injection is reducing the horizontal space of the following table. It looks like this:
![scrn_001](https://cloud.githubusercontent.com/assets/1475675/5164116/7780b976-73d3-11e4-8b09-5d815e5f2189.jpg)

A possible solution could look like this:

``` CSS
.view-content {position:relative;}
#page a.dreditor-application-toggle {position:absolute;right:0;}
```

...and the `float:right;` should be removed. The result then looks like this:
![scrn_002](https://cloud.githubusercontent.com/assets/1475675/5164144/0074c484-73d4-11e4-836c-98e1b8fde9e1.jpg)
